export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const GET_ARTICLE = 'GET_ARTICLE';
export const SUBMIT_FAILURE = 'SUBMIT_FAILURE';
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
export const SUBMIT_ARTICLE_FORM = 'SUBMIT_ARTICLE_FORM';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';
