export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const EDIT_COMMENT_ERROR = 'EDIT_COMMENT_ERROR';
