export const FETCH_HOME_ARTICLES = 'FETCH_HOME_ARTICLES';
export const FETCH_ARTICLES_REQUESTED = 'FETCH_ARTICLES_REQUESTED';
export const FETCH_FEATURED_ARTICLES = 'FETCH_FEATURED_ARTICLES';
export const FETCH_LATEST_ARTICLES = 'FETCH_LATEST_ARTICLES';
export const FETCH_USER_NOTIFICATIONS = 'FETCH_USER_NOTIFICATIONS';
export const ARTICLE_ERROR = 'ARTICLE_ERROR';
