export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAIL = 'CREATE_REPORT_FAIL';
export const GET_REPORT_CATEGORY = 'GET_REPORT_CATEGORY';
export const GET_REPORT_CATEGORY_FAIL = 'GET_REPORT_CATEGORY_FAIL';
