export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_SOCIAL_USER = 'GET_SOCIAL_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
